INSERT INTO songs_entity (id, song_name, song_artist, song_album, song_year)
VALUES

    (UNHEX(REPLACE(UUID(), '-', '')), 'Enter Sandman', 'Metallica', 'Metallica', '1991'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Californication', 'Red Hot Chili Peppers', 'Californication', '1999'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Boulevard of Broken Dreams', 'Green Day', 'American Idiot', '2004'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Numb', 'Linkin Park', 'Meteora', '2003'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Mr. Brightside', 'The Killers', 'Hot Fuss', '2003'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'In the End', 'Linkin Park', 'Hybrid Theory', '2000'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Seven Nation Army', 'The White Stripes', 'Elephant', '2003'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Take Me to Church', 'Hozier', 'Hozier', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Demons', 'Imagine Dragons', 'Night Visions', '2012'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Ride', 'Twenty One Pilots', 'Blurryface', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Riptide', 'Vance Joy', 'Dream Your Life Away', '2013'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Let Her Go', 'Passenger', 'All the Little Lights', '2012'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Say You Won''t Let Go', 'James Arthur', 'Back from the Edge', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Perfect', 'Ed Sheeran', '÷', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Thinking Out Loud', 'Ed Sheeran', 'x', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Photograph', 'Ed Sheeran', 'x', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Someone Like You', 'Adele', '21', '2011'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Hello', 'Adele', '25', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Chasing Pavements', 'Adele', '19', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Use Somebody', 'Kings of Leon', 'Only by the Night', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Sex on Fire', 'Kings of Leon', 'Only by the Night', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Radioactive', 'Kings of Leon', 'Come Around Sundown', '2010'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Iris', 'Goo Goo Dolls', 'Dizzy Up the Girl', '1998'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'How to Save a Life', 'The Fray', 'How to Save a Life', '2005'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'You Found Me', 'The Fray', 'The Fray', '2009'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Counting Blue Cars', 'Dishwalla', 'Pet Your Friends', '1995'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'She Will Be Loved', 'Maroon 5', 'Songs About Jane', '2002'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'This Love', 'Maroon 5', 'Songs About Jane', '2002'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Payphone', 'Maroon 5', 'Overexposed', '2012'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Sugar', 'Maroon 5', 'V', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Maps', 'Maroon 5', 'V', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Closer', 'The Chainsmokers ft. Halsey', 'Collage', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Paris', 'The Chainsmokers', 'Memories...Do Not Open', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Something Just Like This', 'The Chainsmokers & Coldplay', 'Memories...Do Not Open', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Viva La Vida', 'Coldplay', 'Viva la Vida or Death and All His Friends', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Fix You', 'Coldplay', 'X&Y', '2005'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Yellow', 'Coldplay', 'Parachutes', '2000'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'The Scientist', 'Coldplay', 'A Rush of Blood to the Head', '2002'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Speed of Sound', 'Coldplay', 'X&Y', '2005'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Clocks', 'Coldplay', 'A Rush of Blood to the Head', '2002'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Pompeii', 'Bastille', 'Bad Blood', '2013'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Happier', 'Marshmello ft. Bastille', 'Happier (Single)', '2018'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Lean On', 'Major Lazer & DJ Snake', 'Peace Is the Mission', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Rockabye', 'Clean Bandit ft. Anne-Marie', 'Rockabye (Single)', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Rather Be', 'Clean Bandit ft. Jess Glynne', 'New Eyes', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Cheap Thrills', 'Sia ft. Sean Paul', 'This Is Acting', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Chandelier', 'Sia', '1000 Forms of Fear', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Elastic Heart', 'Sia', '1000 Forms of Fear', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Titanium', 'David Guetta ft. Sia', 'Nothing but the Beat', '2011'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Shallow', 'Lady Gaga & Bradley Cooper', 'A Star Is Born', '2018'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Bad Romance', 'Lady Gaga', 'The Fame Monster', '2009'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Poker Face', 'Lady Gaga', 'The Fame', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Born This Way', 'Lady Gaga', 'Born This Way', '2011'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Just Dance', 'Lady Gaga ft. Colby O''Donis', 'The Fame', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Can''t Feel My Face', 'The Weeknd', 'Beauty Behind the Madness', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Blinding Lights', 'The Weeknd', 'After Hours', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Starboy', 'The Weeknd ft. Daft Punk', 'Starboy', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Save Your Tears', 'The Weeknd', 'After Hours', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'The Hills', 'The Weeknd', 'Beauty Behind the Madness', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Uptown Funk', 'Mark Ronson ft. Bruno Mars', 'Uptown Special', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Just the Way You Are', 'Bruno Mars', 'Doo-Wops & Hooligans', '2010'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Grenade', 'Bruno Mars', 'Doo-Wops & Hooligans', '2010'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'That''s What I Like', 'Bruno Mars', '24K Magic', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Treasure', 'Bruno Mars', 'Unorthodox Jukebox', '2012'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Locked Out of Heaven', 'Bruno Mars', 'Unorthodox Jukebox', '2012'),
    (UNHEX(REPLACE(UUID(), '-', '')), '24K Magic', 'Bruno Mars', '24K Magic', '2016'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Shake It Off', 'Taylor Swift', '1989', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Blank Space', 'Taylor Swift', '1989', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Love Story', 'Taylor Swift', 'Fearless', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'You Belong with Me', 'Taylor Swift', 'Fearless', '2008'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Style', 'Taylor Swift', '1989', '2014'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Delicate', 'Taylor Swift', 'Reputation', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Look What You Made Me Do', 'Taylor Swift', 'Reputation', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Anti-Hero', 'Taylor Swift', 'Midnights', '2022'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'All Too Well', 'Taylor Swift', 'Red', '2012'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'drivers license', 'Olivia Rodrigo', 'SOUR', '2021'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'good 4 u', 'Olivia Rodrigo', 'SOUR', '2021'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'deja vu', 'Olivia Rodrigo', 'SOUR', '2021'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'vampire', 'Olivia Rodrigo', 'GUTS', '2023'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'traitor', 'Olivia Rodrigo', 'SOUR', '2021'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Levitating', 'Dua Lipa', 'Future Nostalgia', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Don''t Start Now', 'Dua Lipa', 'Future Nostalgia', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'New Rules', 'Dua Lipa', 'Dua Lipa', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Physical', 'Dua Lipa', 'Future Nostalgia', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Be the One', 'Dua Lipa', 'Dua Lipa', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Stay', 'The Kid LAROI & Justin Bieber', 'F*CK LOVE 3: OVER YOU', '2021'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Peaches', 'Justin Bieber ft. Daniel Caesar & Giveon', 'Justice', '2021'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Sorry', 'Justin Bieber', 'Purpose', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Love Yourself', 'Justin Bieber', 'Purpose', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'What Do You Mean?', 'Justin Bieber', 'Purpose', '2015'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Baby', 'Justin Bieber ft. Ludacris', 'My World 2.0', '2010'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Intentions', 'Justin Bieber ft. Quavo', 'Changes', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Yummy', 'Justin Bieber', 'Changes', '2020'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'As It Was', 'Harry Styles', 'Harry''s House', '2022'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Watermelon Sugar', 'Harry Styles', 'Fine Line', '2019'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Sign of the Times', 'Harry Styles', 'Harry Styles', '2017'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Adore You', 'Harry Styles', 'Fine Line', '2019'),
    (UNHEX(REPLACE(UUID(), '-', '')), 'Late Night Talking', 'Harry Styles', 'Harry''s House', '2022')


ON DUPLICATE KEY UPDATE
                         song_album = VALUES(song_album),
                         song_year = VALUES(song_year);